language: java
    addons:
    sonarcloud:
      organization: "rmedeiros"
      token:
        secure: "XWTfgoLEvK0Lyhm9Kdy5SMF2zre93RTusJYdJY8sPpDbQ0/vt87QW3nYxdE40Xx+IeWvWSE3S6aWKpy4+ONBy++zdwpqH2nZ8OlEjKs+LimZyAZMWSNhA3QjX0LV10ZLQczGQEioekvu9OcqFsc3tho/YQT6FQrrbPhMuxLqe1pCvBt1aJuG2YRvqntyLrbQhp+EAO8x5w1DduFI7f6WR/LlTOFkyZCntrBONwmKWIFx6LfbJloVaMoE1E51Yq8cch3LQc7yiuVV74ktutQ9E8ieTS4v7903Ga21Ad43yOvo00rUcmFswOMZspncnYi5Tr6SUP+5eLqQuYWLQnv2Cmuoh+A+srt/QWkUBMLmYI7drceDV2gkGJ9XiGqGDnBNV42o4N03jotNVHy6i0tEru4Z9Q+nbLii9OWXgSOSta+AwH89Z/j954zpS2R81VPlb4g/qwylQsGShE2+x5GJDMVIxMM8tlk8+NkyK5ZbSTN2DRf2mnlxNfqndhq64BlLxsrb6FpEeKze7Dqpg+dNkXouIkRxPXQJqqo0JsbAZxS2amh5W7EtnUflUE3aSxVjmq+5FmFVLynMYFFLClZMu1Q+MRyxndZPy2pGel3w5nZD1prnwhIm3ouZbpGS8V27oOZiCD00jrKxkZEclVzlSuzeES561DENMNZgocgGHQA="


    script:
    # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
    - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=rmedeiros_featurecloud


    sudo: required
    before_install:
    - sudo apt-get update
    - sudo apt-get install python2.7
    - sudo pip install -r src/main/resources/requirements.txt


    notifications:
    email:
      on_success: change
      on_failure: always