
        - pip install -r src/main/resources/requirements.txt
    - language: java
      notifications:
        email:
          on_success: change
          on_failure: always
      before_install:
      - sudo apt-get update
      - sudo apt-get install python2.7
      - pip install -r src/main/resources/requirements.txt