language: java
notifications:
  email:
    on_success: change
    on_failure: always
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install python2.7
- sudo pip install -r src/main/resources/requirements.txt


addons:
  sonarcloud:
    organization: "rmedeiros"
    token:
      secure: "tIgel3+NOsvy6HHL4d7/WGp8v8h4dA4LUQ2nLCxejzZpSi9Tln0eHLNNC472PHvGnY9J5kxUx7aZOKJPNE7I2jiAWH2gUAnXUgZGmvoZwLbwjq4ieWMqjtUooJz9ALkDtY6xZGOYHX2+E++mxUE1OKo2T1wsRQnoTQJ6loGNMXBNI6WfVj71bgkxEqkZZ12pMf674pYB0uH6Hs1HSI15weVIk7o7k1DLlmftJF/OB/xLDjkZo4Hl2ka84gmi3b2i1NB09F2Z+1Bj9E/guyjQ4qxDM53f4fsUbul3Oy8OUbZhQnbU2K4Djt1XF4bXpIPh/ewj2nUia2XBQkOYwpoMftFgjrA+wpqxO0/KdV0nhLAUtQR68HWoGFIdomidZKC5POBvK631NVmpJmdT5DdliRdZowDZP5JTnEaCLC2p1ha5BRakm70tr3N+2OsNj257LGVqOOsq/Bxjda0qnrJpGFUIHsXV1BIFR6gOYWzbA+DkP+/0hYFh+Q9tUrFYizoDaRD75ctWsm3TclvdEKcpTH/gFew5m5kA96/1BQicWXe2WsderqyM3EBASO5bo/xiW5nnxkWY4Gdpn3SSAbFgoKUl78qumD/ohPdptZUNGg7tQ7lcMy6Loo03jj64Fa52xp9fTj9+/vapkzyXVTPCvCHJ8z4k2OzDfqgE3l164HQ="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=rmedeiros_FeatureCloud
