language: java
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install python2.7
- sudo pip install -r src/main/resources/requirements.txt
addons:
  sonarcloud:
    organization: rmedeiros
    token:
      secure: "MgP1r+94RSGgRZo3wPqWnQCT9Gbx3SOhSYeUH19t3VcP5mPlxf2N2vGQ+BrwDT/CG/NbVhCvedkGhognhUs2fDf4XvfEKM59O/5+i9gGDwuU7HZG0Di6zD8VkyDleZKzYWfhavVhLPpjLUHX6cKrr+JXjC7bdXELUKDSwo/UojOiyzIN71DsknJLwMtEQ7Lz7p8ZYW3IxL92aOeKQMyb8WaNmaO+fBAJnVIWnoTP2qkTGVM5BHIxldjixDB766lb8yZKDdJPtzdSaRbUEJcfoKnS6CMpS65coFaCVjVYzWafJ0I0AGPiVS1Uwg6T7kss2okHsJwRW8e8YrT/xeTesudq7IST+MCJG9Sjzw5b1MX2uFIOp54X+w3l2LVC0Hii5H1AcW15rhqm2nj65x4TcZOyEacOO9+sGF9BBkQgPsaroj0dINwmXSGwwNWnVZX3U36XyDx04Tz+JmjkSTMe9q+0xQfiw1bKsl2wdq8zIKNWWuBsBODkmnghS6v6bzUqn0S/d/8Ylo/wpV+/d/oketWUQGXD4dvI9gzkcvUG7y7zyZOh6araGMeOT5D9CCmSvuyP2JJx+eI1AEjmQfTE/C/FWZQm+zIr/5TsOzKszTi1f8sQ8ucyAogoFu5MyPcUv+mNmRddJeJGGLrMOAzHUBS6OUVDih14Ks4OK5++Xrc="
script:
- mvn clean verify sonar:sonar -Dsonar.projectKey=rmedeiros_FeatureCloud
notifications:
  email:
    on_success: chang
    on_failure: always

