language: java
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install python2.7
- sudo pip install -r src/main/resources/requirements.txt
notifications:
  email:
    on_success: chang
    on_failure: always

